baseURL = "https://skonik.github.io/python-software-patterns"
canonifyURLs = false
languageCode = "en-us"
title = "Python Software Patterns"
theme = "color-your-world"
[params]
    custom_css = ["python-software-patterns/css/custom.css"]
