baseURL = "https://skonik.github.io/python-software-patterns"
canonifyURLs = true
languageCode = "en-us"
title = "Python Software Patterns"
theme = "color-your-world"
[params]
    custom_css = ["css/font.css"]